export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  STUDENT = "STUDENT",
  INSTRUCTOR = "INSTRUCTOR",
  ACCOUNTANT = "ACCOUNTANT",
  PEON = "PEON",
  DISCIPLINE_IN_CHARGE = "DISCIPLINE_IN_CHARGE",
  ADMINISTRATIVE_OFFICER = "ADMINISTRATIVE_OFFICER",
  FINANCE_OFFICER = "FINANCE_OFFICER"
}


